# Generated by Django 4.2.1 on 2023-05-31 07:29

from django.db import migrations, models
import todo.models


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0002_alter_tag_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="due_date",
            field=models.DateField(
                blank=True, null=True, validators=[todo.models.validate_due_date]
            ),
        ),
    ]
